spring:
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 47.95.215.227 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: wefun123
    timeout: 0 # 连接超时时间（毫秒）
    pool:
      max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 100 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
