permission:
  permissionInfo:
    commonPermissionList:
      - prefix: /rest/test
      - prefix: /rest/admin
    specificPermissionList:
      - url: /rest/admin/login
        perms: /rest/admin:login
        roles: