server:
  port: 8082

spring:
  profiles:
    include: dubbo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111